name: my first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repository
          uses: actions/checkout@v4

        - name: welcome message
          run: echo "my first Github Action"

        - name: list files
          run: ls
        
        - name: Read file
          run: cat README.md
          

#The steps above can be done in one step. using multiline command

        - name: all steps
          run: |
            echo "A new way to do all these"
            ls -ltra
            cat README.md

# #we can also use 3rd party library

#         - name: Generate ASCII artwork
#           run: cowsay -f dragon "Run for cover, I am a DRAGON......RAWR" >> dragon.txt
          #cowsay is an ascii library use for generating artwork and it shows a cowing saying something, however, the animal can be changes using the "-f" flag followed by the animal name
          #for context, this step will fail if the "cowsay" library is not installed on the ubuntu machine, and this can be done with an initial step before this
              


